name: Build and Deploy to Production

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Copy source to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "."
          target: "/home/ubuntu/app-build"
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            export PATH="/usr/local/bin:/usr/bin:/bin:$PATH"
            cd /home/ubuntu/app-build
            echo "${{ secrets.NPMRC }}" > .npmrc
            PNPM_PATH=$(which pnpm || echo "/usr/local/bin/pnpm")
            $PNPM_PATH install --frozen-lockfile
            $PNPM_PATH run build
            rm .npmrc

  dockerize:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /home/ubuntu/app-build
            docker build --no-cache -t ai-paas-web:latest .
            docker save ai-paas-web:latest > ai-paas-web.tar

  deploy:
    needs: dockerize
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            docker load < /home/ubuntu/app-build/ai-paas-web.tar

            docker stop ai-paas-web || true
            docker rm ai-paas-web || true

            docker run -d \
              --name ai-paas-web \
              -p 80:80 \
              -e VITE_SERVER_URL=${{ secrets.SERVER_URL }} \
              --restart always \
              ai-paas-web:latest

            docker image prune -f
